name: nimir
description: "An anonymous platform to report women harassment!"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.3.3
  google_sign_in: ^6.2.2
  fluttertoast: ^8.2.8
  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.0
  google_ml_kit: ^0.19.0
  image_picker: ^1.1.2
  firebase_storage: ^12.3.6
  firebase_ml_model_downloader: ^0.3.1+5
  firebase_messaging: ^15.1.5
  cloud_firestore: ^5.5.0
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  image: ^4.3.0
  firebase_app_check: ^0.3.1+6
  encrypt: ^5.0.3
  carousel_slider: ^5.0.0
  intl: ^0.19.0
  random_avatar: ^0.0.8
  flutter_sound: ^9.17.0
  permission_handler: ^11.3.1
  url_launcher: ^6.3.1
  dart_sentiment: ^0.0.9
  flutter_tts: ^4.2.0
  http: ^1.2.2
  path_provider: ^2.1.5
  text2pdf: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/google_logo.png
    - assets/logo.png


